# Pre-commit hooks configuration for ADB-UTIL
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  # Python code formatting
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=88]

  # Import sorting
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [--profile=black, --line-length=88]

  # Linting
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: [--max-line-length=88, --extend-ignore=E203,W503,E501]

  # Type checking (disabled due to PyQt6 type compatibility issues)
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.8.0
  #   hooks:
  #     - id: mypy
  #       args: [--ignore-missing-imports, --no-strict-optional]

  # General hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # File checks
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files

      # Python checks
      - id: check-ast
      - id: check-docstring-first
      - id: debug-statements
      - id: name-tests-test

      # Security checks
      - id: detect-private-key

  # Custom hooks for ADB-UTIL
  - repo: local
    hooks:
      # Run tests before commit (optional - can be slow)
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
        always_run: false
        stages: [pre-push]
        args: [tests/, -v, --tb=short]

      # Check if main.py can be imported
      - id: check-main-import
        name: Check main module import
        entry: python
        language: system
        pass_filenames: false
        args: [-c, "import sys; sys.path.insert(0, '.'); import main"]

# Configuration
default_install_hook_types: [pre-commit, pre-push]
fail_fast: false
minimum_pre_commit_version: 3.0.0

# Exclude patterns
exclude: |
  (?x)^(
    \.venv/.*|
    venv/.*|
    build/.*|
    dist/.*|
    \.git/.*|
    __pycache__/.*|
    \.pytest_cache/.*|
    \.mypy_cache/.*|
    \.coverage.*|
    .*\.egg-info/.*
  )$
